### ISSUE TITLE
Panic with atom:link element

### ISSUE THREAD

**Issue by vanbroup** [sbabiv/xml2map#8]
A panic is triggered while decoding atom document with:

```
<atom:link href="http://www.example.com/rss.xml" rel="self" type="application/rss+xml" />
```

```
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 1 [running]:
github.com/sbabiv/xml2map.setNodeValue(0xc000060230)
	/tmp/gopath700616318/pkg/mod/github.com/sbabiv/xml2map@v1.2.0/decoder.go:138 +0x965
github.com/sbabiv/xml2map.(*Decoder).Decode(0xc000086f40)
	/tmp/gopath700616318/pkg/mod/github.com/sbabiv/xml2map@v1.2.0/decoder.go:109 +0x2af
main.main()
	/tmp/sandbox2063523566/prog.go:29 +0xb6
```

Removing the `:link` suffix from the element resolves the issue, see also this example:

https://play.golang.org/p/E8qc16pry6-

**Comment by sbabiv** [comment]
@vanbroup thanks for the fix. merged!
